const SampleIssue = {
  url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926",
  repository_url: "https://api.github.com/repos/FreeTubeApp/FreeTube",
  labels_url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926/labels{/name}",
  comments_url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926/comments",
  events_url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926/events",
  html_url: "https://github.com/FreeTubeApp/FreeTube/issues/6926",
  id: 2880387690,
  node_id: "I_kwDOB1gwuM6rrzpq",
  number: 6926,
  title: "[Feature Request]: Keyboard Shortcut to Reset Playback Speed to 1x",
  user: {
    login: "jasiralavi",
    id: 16372030,
    node_id: "MDQ6VXNlcjE2MzcyMDMw",
    avatar_url: "https://avatars.githubusercontent.com/u/16372030?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jasiralavi",
    html_url: "https://github.com/jasiralavi",
    followers_url: "https://api.github.com/users/jasiralavi/followers",
    following_url: "https://api.github.com/users/jasiralavi/following{/other_user}",
    gists_url: "https://api.github.com/users/jasiralavi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jasiralavi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jasiralavi/subscriptions",
    organizations_url: "https://api.github.com/users/jasiralavi/orgs",
    repos_url: "https://api.github.com/users/jasiralavi/repos",
    events_url: "https://api.github.com/users/jasiralavi/events{/privacy}",
    received_events_url: "https://api.github.com/users/jasiralavi/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
  },
  labels: [
    {
      id: 850957755,
      node_id: "MDU6TGFiZWw4NTA5NTc3NTU=",
      url: "https://api.github.com/repos/FreeTubeApp/FreeTube/labels/enhancement",
      name: "enhancement",
      color: "a2eeef",
      default: true,
      description: "New feature or request",
    },
    {
      id: 3710114744,
      node_id: "LA_kwDOB1gwuM7dI9u4",
      url: "https://api.github.com/repos/FreeTubeApp/FreeTube/labels/E:%20keyboard%20shortcut",
      name: "E: keyboard shortcut",
      color: "ededed",
      default: false,
      description: null,
    },
  ],
  state: "open",
  locked: false,
  assignee: null,
  assignees: [],
  milestone: null,
  comments: 0,
  created_at: "2025-02-26T06:32:16Z",
  updated_at: "2025-02-26T06:32:29Z",
  closed_at: null,
  author_association: "NONE",
  sub_issues_summary: {
    total: 0,
    completed: 0,
    percent_completed: 0,
  },
  active_lock_reason: null,
  body: "### Guidelines\n\n- [x] I have [searched the issue tracker for open and closed issues](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+sort%3Arelevance-desc) that are similar to the feature request I want to file, without success.\n- [x] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.\n- [x] This issue contains only one feature request.\n\n### Problem Description\n\nIf the playback speed is increased / decreased to an odd multiple of 5 (either with Ctrl+scroll or due to other configurations insettings), it's not easy to get back to normal speed (1x or whatever is defined in settings by the user). \nAlso the Ctrl + Left-click doesn't seem to be working.\n\n### Proposed Solution\n\nCan we consider a shortcut key (may be `|`) to reset to normal playback speed?\n\n### Alternatives Considered\n\nCtrl + Left-click as mentioned (although it's not a shortcut key).\nBut it  doesn't seem to be working anyway.\n\n### Issue Labels\n\nnew keyboard shortcut\n\n### Additional Information\n\n_No response_",
  closed_by: null,
  reactions: {
    url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926/reactions",
    total_count: 0,
    "+1": 0,
    "-1": 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  },
  timeline_url: "https://api.github.com/repos/FreeTubeApp/FreeTube/issues/6926/timeline",
  performed_via_github_app: null,
  state_reason: null,
};

const LocalIssue = {
  id: 1,
  repo_name: "test",
  issue_url: "test",
  issue_id: "test",
  issue_title: "test",
  issue_author_name: "test",
  issue_author_profile: "test",
  issue_number: "test",
  created_at: "2025-02-26T13:01:35.720Z",
  updated_at: "2025-02-26T13:01:35.720Z",
};

export type IssueType = typeof SampleIssue & typeof LocalIssue;
export type LocalIssueType = typeof LocalIssue;
